theme: jekyll-theme-cayman
title: <a href="https://rocknroll87q.github.io/self-supervised_inpainting/">Self-Supervised DNN and EVC fMRI activity </a>
description: A Self-Supervised Deep Neural Network for Image Completion Resembles Early Visual Cortex fMRI Activity Patterns for Occluded Scenes

show_downloads: [true]

github:
  zip_url: https://github.com/rockNroll87q/self-supervised_inpainting
  another_url: https://www.biorxiv.org/content/early/2020/12/13/2020.03.24.005132
